definitions:
  jsonutil.ResponseData:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
info:
  contact: {}
  title: 男生自用 API 接口文档
  version: "1.0"
paths:
  /api/cli/module/create:
    get:
      consumes:
      - application/json
      description: get string by ID
      parameters:
      - description: 模块名称
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: res
          schema:
            allOf:
            - $ref: '#/definitions/jsonutil.ResponseData'
            - properties:
                data:
                  type: boolean
              type: object
      summary: 创建模块
      tags:
      - cli
  /api/user/list:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: res
          schema:
            $ref: '#/definitions/jsonutil.ResponseData'
      summary: 用户列表
      tags:
      - user
swagger: "2.0"
