definitions:
  cli.CreateModuleBody:
    properties:
      name:
        description: 模块名称
        type: string
    type: object
  resp.Result:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  user.CreateUserBodyDto:
    properties:
      name:
        description: 姓名
        type: string
      sex:
        description: 性别
        type: string
    required:
    - name
    - sex
    type: object
info:
  contact: {}
  title: 男生自用 API 接口文档
  version: "1.0"
paths:
  /api/cli/module/create:
    post:
      consumes:
      - application/json
      description: get string by ID
      parameters:
      - description: 模块名称
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/cli.CreateModuleBody'
      produces:
      - application/json
      responses:
        "200":
          description: resp
          schema:
            allOf:
            - $ref: '#/definitions/resp.Result'
            - properties:
                data:
                  type: boolean
              type: object
        "500":
          description: resp
          schema:
            allOf:
            - $ref: '#/definitions/resp.Result'
            - properties:
                data:
                  type: string
              type: object
      summary: 创建模块
      tags:
      - cli
  /api/user/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/user.CreateUserBodyDto'
      produces:
      - application/json
      responses:
        "200":
          description: resp
      summary: 创建用户
      tags:
      - user
  /api/user/list:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: resp
          schema:
            type: string
      summary: 用户列表
      tags:
      - user
swagger: "2.0"
