// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q         = new(Query)
	Account   *account
	AdminRole *adminRole
	AdminUser *adminUser
	Captcha   *captcha
	News      *news
	User      *user
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Account = &Q.Account
	AdminRole = &Q.AdminRole
	AdminUser = &Q.AdminUser
	Captcha = &Q.Captcha
	News = &Q.News
	User = &Q.User
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:        db,
		Account:   newAccount(db, opts...),
		AdminRole: newAdminRole(db, opts...),
		AdminUser: newAdminUser(db, opts...),
		Captcha:   newCaptcha(db, opts...),
		News:      newNews(db, opts...),
		User:      newUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Account   account
	AdminRole adminRole
	AdminUser adminUser
	Captcha   captcha
	News      news
	User      user
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:        db,
		Account:   q.Account.clone(db),
		AdminRole: q.AdminRole.clone(db),
		AdminUser: q.AdminUser.clone(db),
		Captcha:   q.Captcha.clone(db),
		News:      q.News.clone(db),
		User:      q.User.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:        db,
		Account:   q.Account.replaceDB(db),
		AdminRole: q.AdminRole.replaceDB(db),
		AdminUser: q.AdminUser.replaceDB(db),
		Captcha:   q.Captcha.replaceDB(db),
		News:      q.News.replaceDB(db),
		User:      q.User.replaceDB(db),
	}
}

type queryCtx struct {
	Account   IAccountDo
	AdminRole IAdminRoleDo
	AdminUser IAdminUserDo
	Captcha   ICaptchaDo
	News      INewsDo
	User      IUserDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Account:   q.Account.WithContext(ctx),
		AdminRole: q.AdminRole.WithContext(ctx),
		AdminUser: q.AdminUser.WithContext(ctx),
		Captcha:   q.Captcha.WithContext(ctx),
		News:      q.News.WithContext(ctx),
		User:      q.User.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
